# .github/workflows/main.yml

name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-ruby-2-4-x:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
      - name: Build and run tests
        env:
          BUNDLE_GEMFILE: "Gemfile-Ruby-2-4"
        run: |
          gem install bundler -v 2.3
          bundle install --jobs 4 --retry 3
          bundle exec rake

  test-ruby-2-5-x:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Build and run tests
        env:
          BUNDLE_GEMFILE: "Gemfile-Ruby-2-5"
        run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3
          bundle exec rake

  test-ruby:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
        ruby-version: ["2.6", "2.7", "3.0", "3.1", "3.2"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Build and run tests
        run: |
          gem install bundler -v 2.4.6
          bundle install --jobs 4 --retry 3
          bundle exec rake
