name: Skunk
on: [push]

jobs:
  skunk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Run test suite with COVERAGE=true
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          COVERAGE=true bundle exec rake test
      - name: Run Skunk on Project
        run: |
          gem install skunk
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          if [[ "$CURRENT_BRANCH" != "master" ]]; then
            echo "Executing within branch: $CURRENT_BRANCH"
            skunk lib/ -b master
          else
            echo "Executing within master branch"
            skunk lib/
          fi
